export const FETCH_USER = "FETCH_USER";
export const UPDATE_TASK_SCORE = "FETCH_TASKS";
export const UPDATE_TASK_SCORE_SUCCESS = "FETCH_TASKS_SUCCESS";
export const UPDATE_TASK_SCORE_ERROR = "FETCH_TASKS_ERROR";
export const SHOW_FEEDBACK = "SHOW_FEEDBACK";
